services:
  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USER=
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_DB=
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

volumes:
  postgres_data: {}